Bia converter tests with local api (#320)
* Minor fix to mocking requests.get

* Save WIP - testing bia-converter with API

* Reverse changes made to mock request get

* Fix issues causing ci/cd tests to fail

* Make tests check image representation created in api and output file created

* Allow update of existing objects when saving objects to api

* Temporarily modify CI/CD to run pytest verbosely to investigate errors occuring in CI/CD tests

* Temporarily modify CI/CD to run pytest verbosely to investigate errors occuring in CI/CD tests. Attempt 2

* More minor changes to make tests work in Github CI/CD

* Revert changes to github workflow

* Save WIP addressing PR comments

* Address PR comments

* Bump ubuntu to 22.04 as 20.04 is being deprecated in github ci/cd

* Try purging pip cache before install to address - ImportError: cannot import name 'cbuffer_sizes' from 'numcodecs.blosc'

* Try pinning numcodecs in pyproject.toml to fix dependency error in github ci/cd

* Another attempt to fix numcodecs dependency error in github ci/cd

* Try purging pip cache before install to address - ImportError: cannot import name 'cbuffer_sizes' from 'numcodecs.blosc'

* Another attempt to fix numcodes import error in CI/CD

* Another attempt to fix numcodes import error in CI/CD

* Another attempt to fix numcodes import error in CI/CD

* Fix numcodes import error in CI/CD by pinning version to <=0.14.1